In [1]:
# 1
import numpy as np
arr = np.random.randint(10, 50, size=20)
mean_value = np.mean(arr)
std_value = np.std(arr)
print("Array:", arr)
print("Mean:", mean_value)
print("Sd:", std_value)

Array: [10 44 24 32 48 45 14 41 34 23 10 17 40 18 15 46 45 35 19 27]
Mean: 29.35
Sd: 12.830724843125584


In [2]:
# 2
array = np.random.rand(6, 5)
reshaped_array = array.reshape(5, 6)
print("Original (6,5) Array:\n", array)
print("\nReshaped (5,6) Array:\n", reshaped_array)

Original (6,5) Array:
 [[0.55054182 0.59177395 0.09127873 0.29316007 0.91900005]
 [0.93607359 0.30813789 0.22587428 0.91551435 0.28595379]
 [0.21198687 0.90006407 0.67694531 0.99875522 0.5599175 ]
 [0.19407875 0.78129677 0.33136904 0.74479538 0.07973345]
 [0.53471419 0.67097554 0.3043865  0.90199076 0.33952814]
 [0.99517962 0.54594688 0.42166731 0.4326978  0.8782921 ]]

Reshaped (5,6) Array:
 [[0.55054182 0.59177395 0.09127873 0.29316007 0.91900005 0.93607359]
 [0.30813789 0.22587428 0.91551435 0.28595379 0.21198687 0.90006407]
 [0.67694531 0.99875522 0.5599175  0.19407875 0.78129677 0.33136904]
 [0.74479538 0.07973345 0.53471419 0.67097554 0.3043865  0.90199076]
 [0.33952814 0.99517962 0.54594688 0.42166731 0.4326978  0.8782921 ]]


In [3]:
# 3
array = np.arange(1, 26).reshape(5, 5)
subarray = array[2:5, 1:4]
print("Array:\n", array)
print("\nSubarray:\n", subarray)

Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Subarray:
 [[12 13 14]
 [17 18 19]
 [22 23 24]]


In [4]:
# 4
A = np.random.randint(1, 100, 10)
B = np.random.randint(1, 100, 10)
sum_array = A + B
final_result = sum_array * 2
print("Array A:", A)
print("Array B:", B)
print("Sum of A and B:", sum_array)
print("Final Result (Sum * 2):", final_result)


Array A: [52 89 19 11 14  7 15 37 33 17]
Array B: [74 30 37 98  7 34  7 67 86 74]
Sum of A and B: [126 119  56 109  21  41  22 104 119  91]
Final Result (Sum * 2): [252 238 112 218  42  82  44 208 238 182]


In [5]:
# 5
A = np.random.randint(1, 10, (3, 4))
B = np.array([1, 2, 3, 4])
result = A + B
print("Array A:\n", A)
print("\nArray B:\n", B)
print("\nResult:\n", result)

Array A:
 [[4 4 7 7]
 [6 2 7 9]
 [4 5 3 4]]

Array B:
 [1 2 3 4]

Result:
 [[ 5  6 10 11]
 [ 7  4 10 13]
 [ 5  7  6  8]]


In [6]:
# 6
matrix = np.random.randint(1, 100, (3, 3))
row_sums = np.sum(matrix, axis=1)
max_row_index = np.argmax(row_sums)
max_value_in_row = np.max(matrix[max_row_index])
print(matrix)
print(row_sums)
print(max_row_index)
print(max_value_in_row)

[[15 98 60]
 [69  7  5]
 [30 47 88]]
[173  81 165]
0
98


In [7]:
# 7
A = np.random.randint(1, 10, (2, 2))
B = np.random.randint(1, 10, (2, 2))
result = np.dot(A, B)
print(A)
print(B)
print(result)

[[6 5]
 [6 8]]
[[1 5]
 [6 2]]
[[36 40]
 [54 46]]


In [8]:
# 8
matrix = np.random.randint(1, 50, (6, 6))
values_greater_than_25 = matrix[matrix > 25]
print(matrix)
print(values_greater_than_25)

[[21 35 11 49 42  3]
 [36 12 16 25  2  4]
 [24 20 13 15 43  9]
 [47 28 25 33 28 31]
 [ 5 10 22 35 32 37]
 [36  3 12 26  2 44]]
[35 49 42 36 43 47 28 33 28 31 35 32 37 36 26 44]


In [9]:
# 9
matrix = np.random.rand(5, 5)
median_columns = np.median(matrix, axis=0)
median_rows = np.median(matrix, axis=1)
variance_columns = np.var(matrix, axis=0)
variance_rows = np.var(matrix, axis=1)
print(matrix)
print(median_columns)
print(median_rows)
print(variance_columns)
print(variance_rows)

[[0.89940862 0.90866836 0.19905728 0.68360031 0.48122402]
 [0.72495714 0.52080182 0.36643118 0.90489406 0.74886694]
 [0.262805   0.89323046 0.62220072 0.92708404 0.63659773]
 [0.31954676 0.65040819 0.03495358 0.8822628  0.7710717 ]
 [0.63875136 0.63446307 0.90625935 0.62827128 0.89373498]]
[0.63875136 0.65040819 0.36643118 0.8822628  0.74886694]
[0.68360031 0.72495714 0.63659773 0.65040819 0.63875136]
[0.058868   0.02348652 0.09542245 0.01536471 0.01933136]
[0.07217191 0.03548336 0.05702385 0.09721014 0.01702976]


In [10]:
# 10
matrix = np.random.randint(1, 10, (3, 3))
subtracted_matrix = matrix - 2 
squared_matrix = subtracted_matrix* 2  
reciprocal_matrix = np.reciprocal(squared_matrix.astype(float)) 
print(matrix)
print(subtracted_matrix)
print(squared_matrix)
print(reciprocal_matrix)

[[2 9 4]
 [6 1 9]
 [4 3 8]]
[[ 0  7  2]
 [ 4 -1  7]
 [ 2  1  6]]
[[ 0 14  4]
 [ 8 -2 14]
 [ 4  2 12]]
[[        inf  0.07142857  0.25      ]
 [ 0.125      -0.5         0.07142857]
 [ 0.25        0.5         0.08333333]]


C:\Users\HP\AppData\Local\Temp\ipykernel_3364\3736935200.py:5: RuntimeWarning: divide by zero encountered in reciprocal
  reciprocal_matrix = np.reciprocal(squared_matrix.astype(float))


In [11]:
# pandas
import pandas as pd


In [19]:
#1
df = pd.read_csv('auto-mpg.csv')
df.head(10)


mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   
5  15.0          8         429.0        198    4341          10.0          70   
6  14.0          8         454.0        220    4354           9.0          70   
7  14.0          8         440.0        215    4312           8.5          70   
8  14.0          8         455.0        225    4425          10.0          70   
9  15.0          8         390.0        190    3850           8.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino  
5       1           ford galaxie 500  
6       1           chevrolet impala  
7       1          plymouth fury iii  
8       1           pontiac catalina  
9       1         amc ambassador dpl

In [20]:
print(df.shape)
df.describe()

(398, 9)


mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

In [21]:
# 2
df[(df['model year'] == 75) & (df['weight'] < 3000)][['car name', 'weight', 'mpg']]


car name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0

In [22]:
# 3
df.isna().sum()



mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [26]:
hp = df[(df['horsepower']!='?')]['horsepower'].astype(int).median()
hps= df['horsepower'].values
hps[hps=='?']=hp
df['horsepower']=hps.astype(int)
df['horsepower']

0      130
1      165
2      150
3      150
4      140
      ... 
393     86
394     52
395     84
396     79
397     82
Name: horsepower, Length: 398, dtype: int64

In [27]:
df


mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0         130    3504          12.0   
1    15.0          8         350.0         165    3693          11.5   
2    18.0          8         318.0         150    3436          11.0   
3    16.0          8         304.0         150    3433          12.0   
4    17.0          8         302.0         140    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0          86    2790          15.6   
394  44.0          4          97.0          52    2130          24.6   
395  32.0          4         135.0          84    2295          11.6   
396  28.0          4         120.0          79    2625          18.6   
397  31.0          4         119.0          82    2720          19.4   

     model year  origin                   car name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]

In [30]:
# 4
df['power_to_weight_ratio'] = df['horsepower'] / df['weight']
df.head()


mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0         130    3504          12.0   
1  15.0          8         350.0         165    3693          11.5   
2  18.0          8         318.0         150    3436          11.0   
3  16.0          8         304.0         150    3433          12.0   
4  17.0          8         302.0         140    3449          10.5   

   model year  origin                   car name  power_to_weight_ratio  
0          70       1  chevrolet chevelle malibu               0.037100  
1          70       1          buick skylark 320               0.044679  
2          70       1         plymouth satellite               0.043655  
3          70       1              amc rebel sst               0.043694  
4          70       1                ford torino               0.040591

In [31]:
# 5
print(df.groupby('origin')['mpg'].mean())


origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64


In [33]:
# 6
df_mpg_sort = df.sort_values(by='mpg', ascending=False)
df_mpg_sort.head(10)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
322  46.6          4          86.0          65    2110          17.9   
329  44.6          4          91.0          67    1850          13.8   
325  44.3          4          90.0          48    2085          21.7   
394  44.0          4          97.0          52    2130          24.6   
326  43.4          4          90.0          48    2335          23.7   
244  43.1          4          90.0          48    1985          21.5   
309  41.5          4          98.0          76    2144          14.7   
330  40.9          4          85.0          93    1835          17.3   
324  40.8          4          85.0          65    2110          19.2   
247  39.4          4          85.0          70    2070          18.6   

     model year  origin                         car name  \
322          80       3                        mazda glc   
329          80       3              honda civic 1500 gl   
325          80       2             vw rabbit c (diesel)   
394          82       2                        vw pickup   
326          80       2               vw dasher (diesel)   
244          78       2  volkswagen rabbit custom diesel   
309          80       2                        vw rabbit   
330          80       2             renault lecar deluxe   
324          80       3                       datsun 210   
247          78       3                   datsun b210 gx   

     power_to_weight_ratio  
322               0.030806  
329               0.036216  
325               0.023022  
394               0.024413  
326               0.020557  
244               0.024181  
309               0.035448  
330               0.050681  
324               0.030806  
247               0.033816

In [34]:
#7
def performance_score(row): 
    return row['mpg'] * row['acceleration'] / row['weight']

In [35]:
df['performance_score'] = df.apply(performance_score,axis =1)
df[['mpg','acceleration','weight','performance_score']].head()

mpg  acceleration  weight  performance_score
0  18.0          12.0    3504           0.061644
1  15.0          11.5    3693           0.046710
2  18.0          11.0    3436           0.057625
3  16.0          12.0    3433           0.055928
4  17.0          10.5    3449           0.051754

In [37]:
# 8
df.groupby('model year')[['mpg', 'weight', 'horsepower']].mean()

mpg       weight  horsepower
model year                                    
70          17.689655  3372.793103  147.827586
71          21.250000  2995.428571  106.535714
72          18.714286  3237.714286  120.178571
73          17.100000  3419.025000  130.475000
74          22.703704  2877.925926   94.185185
75          20.266667  3176.800000  101.066667
76          21.573529  3078.735294  101.117647
77          23.375000  2997.357143  105.071429
78          24.061111  2861.805556   99.694444
79          25.093103  3055.344828  101.206897
80          33.696552  2436.655172   78.551724
81          30.334483  2522.931034   81.448276
82          31.709677  2453.548387   81.838710

In [39]:
# 9
df[df['mpg'] > 30][['mpg', 'cylinders', 'horsepower', 'weight']].to_csv('high_mpg_cars.csv', index=False)


In [42]:
# 10
Q1, Q3 = df['mpg'].quantile([0.25, 0.75])
IQR = Q3 - Q1
outliers = df[(df['mpg'] < Q1 - 1.5 * IQR) | (df['mpg'] > Q3 + 1.5 * IQR)]
outliers[['car name', 'mpg', 'model year']]


car name   mpg  model year
322  mazda glc  46.6          80